language: cpp

dist: xenial
addons:
  apt:
    packages:
      - libace-dev
      - libace-ssl-dev
      - libace-inet-dev
      - libace-inet-ssl-dev
      - libtinyxml-dev
      - zlib1g-dev
      - libssl-dev
      - libopus-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libvpx-dev
      - libogg-dev
      - portaudio19-dev
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
      - openjdk-8-jdk
      - cmake
      - qt5-default
      - qtmultimedia5-dev
      - libqt5x11extras5-dev
      - libqt5webkit5-dev
#      - qtwebengine5-dev (ubuntu 18)
      - junit4
      - catch
      - python3-minimal
      - doxygen

# Library/TeamTalkLib/toolchain has many submodules
git:
  submodules: false

env:
  global:
# TeamTalkJNI JUnit environment variables
    - INPUTDEVICEID=1978
    - OUTPUTDEVICEID=1978
    - OPUSTOOLS=0
    - VERBOSE=0

script:
# Source env (LD_LIBRARY_PATH, PYTHONPATH, etc)
  - cd $TRAVIS_BUILD_DIR
  - source env.sh
# Build libraries, server binaries and examples
  - mkdir build
  - cd build
  - cmake -DBUILD_TEAMTALK_CORE=ON -DBUILD_TEAMTALK_STATIC=OFF -DBUILD_TEAMTALK_ACE=OFF -DSPEEXDSP_STATIC=OFF -DFFMPEG_STATIC=OFF -DAVF=OFF -DMSDMO=OFF -DDSHOW=OFF -DVIDCAP=OFF -DMEDIAFOUNDATION=OFF -DOPUS_STATIC=OFF -DLIBVPX_STATIC=OFF -DSPEEX_STATIC=OFF -DOGG_STATIC=OFF -DOPUSTOOLS=OFF -DLAMEMP3=OFF -DMSVS_UNITTEST=OFF -DACE_STATIC=OFF -DTINYXML_STATIC=OFF -DPORTAUDIO=OFF -DZLIB_STATIC=OFF -DCATCH_UNITTEST=ON -DCMAKE_BUILD_TYPE=debug ..
  - make -j4
# Start TeamTalk Standard Server non-encrypted mode for JUnit and Catch
  - cd $TRAVIS_BUILD_DIR
  - cp Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
  - Server/tt5srv -d -c Server/tt5srv.xml
# Run JUnit suite TeamTalkStdTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - make runjunit
# Kill TeamTalk Standard Server non-encrypted mode
  - killall tt5srv
# Start TeamTalk Pro Server non-encrypted mode for JUnit
# and use shared audio device
  - cd $TRAVIS_BUILD_DIR
  - cp -f Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
  - Server/tt5prosrv -d -c Server/tt5srv.xml
# Run JUnit suite TeamTalkProTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - export ENCRYPTED=0
  - export INPUTDEVICEID=4026
  - export OUTPUTDEVICEID=4026
  - make runjunitpro
  - killall tt5prosrv
